# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e425afbf355f64b113cad891c02d7908a989cafb5ef3bf7edb95460970c2c93bf3b38205c6c25a07a58798408d482f32921079563466867062338ea0dff97db9

test:
  secret_key_base: 29cd26adc345fc0982de8432b8ff71af779d2efa03f3be8ddb5e79fa5b8f04fbdd137538fb4baedbb4471eb3b52cf728116657c30bad961a0fb760aa29a5ea74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
